version: 2.1

orbs:
  git: mavenlink/git@dev:$CIRCLE_SHA1

executors:
  base:
    docker:
      - image: docker:stable-git

jobs:
  build:
    executor: base
    steps:
      - checkout
      - run: ssh-add ~/project/.ssh/id_rsa
      - git/checkout
      - run: test $(git log --pretty=format:'' | wc -l) -eq 1
