version: 2.1

orbs:
  git: mavenlink/git@dev:$CIRCLE_SHA1

executors:
  base:
    docker:
      - image: docker:stable-git

jobs:
  build:
    executor: base
    steps:
      - checkout
      - git/checkout
