version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.1
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  schema-validations:
    jobs:
      - git-schema-validation

jobs:
  git-schema-validation:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/git/orb.yml
