version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.1
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  git:
    jobs:
      - git-schema-validation
      - git-publish-sha:
          requires:
            - git-schema-validation
      - git-integration-test:
          requires:
            - git-publish-sha

jobs:
  git-schema-validation:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/git/orb.yml
  git-publish-sha:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/publish:
          orb-path: src/git/orb.yml
          orb-ref: mavenlink/git@dev:$CIRCLE_SHA1
          token-variable: $ORB_PUBLISHING_TOKEN
  git-integration-test:
    machine:
      image: circleci/classic:latest
    steps:
      - cli/install
      - checkout
      - run: sed -i -e 's/$CIRCLE_SHA1/'$CIRCLE_SHA1'/g' src/git/config.yml
      - run: circleci config process src/git/config.yml > src/git/processed_config.yml
      - run: circleci local execute -c src/git/processed_config.yml
